name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          include-prerelease: true
      - name: Restore
        run: dotnet restore DemiCatPlugin/DemiCatPlugin.csproj
      - name: Build
        run: dotnet build DemiCatPlugin/DemiCatPlugin.csproj --configuration Release
      - name: Test
        if: ${{ hashFiles('**/*Tests.csproj') != '' }}
        run: dotnet test tests --configuration Release
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run backend tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r demibot/requirements-dev.txt
          pytest

